In [14]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.utils import class_weight
import lightgbm as lgb
import copy


pd.set_option('display.max_columns', None)

In [16]:
path_set = "/Users/Martijn.Beeks/Development/Personal/pred-maintenance/pred-maintenance/data/water_pump_set.csv"
path_labels = "/Users/Martijn.Beeks/Development/Personal/pred-maintenance/pred-maintenance/data/water_pump_labels.csv"

In [17]:
df_set = pd.read_csv(path_set, index_col=0)
df_labels = pd.read_csv(path_labels)

# Exploratory data analysis

In [18]:
df_set.head()

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [19]:
df_set.describe()

,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
count,59400.000000,59400.000000,59400.000000,5.940000e+04,59400.000000,59400.000000,59400.000000,59400.000000,59400.000000
mean,317.650385,668.297239,34.077427,-5.706033e+00,0.474141,15.297003,5.629747,179.909983,1300.652475
std,2997.574558,693.116350,6.567432,2.946019e+00,12.236230,17.587406,9.633649,471.482176,951.620547
min,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,1.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,33.090347,-8.540621e+00,0.000000,5.000000,2.000000,0.000000,0.000000
50%,0.000000,369.000000,34.908743,-5.021597e+00,0.000000,12.000000,3.000000,25.000000,1986.000000
75%,20.000000,1319.250000,37.178387,-3.326156e+00,0.000000,17.000000,5.000000,215.000000,2004.000000
max,350000.000000,2770.000000,40.345193,-2.000000e-08,1776.000000,99.000000,80.000000,30500.000000,2013.000000

In [73]:
df_temp.isna().sum()

amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
status_group                 0
dtype: int64

### Step 1: Select numerical and categorical data

In [20]:
# Get numerical and categorical variables

In [69]:
num_cols_switch = ['region_code', 'district_code', 'construction_year']
cols_drop = ['gps_height', 'longitude', 'latitude']
remove_cat_columns = ['wpt_name', 'installer', 'funder', 'subvillage', 'ward', 'scheme_name']


def get_feature_types(df_set, num_cols_switch=num_cols_switch, cols_drop=cols_drop, remove_cat_columns=remove_cat_columns):
    numerical_cols = list(df_set._get_numeric_data().columns)
    categorical_cols = list(set(df_set.columns) - set(numerical_cols))
    
    numerical_cols = [x for x in numerical_cols if x not in num_cols_switch]
    categorical_cols.extend(num_cols_switch)
    
    numerical_cols = [x for x in numerical_cols if x not in cols_drop]
    
    for drop_column in remove_cat_columns:
        if drop_column in categorical_cols:
            categorical_cols = [x for x in categorical_cols if x not in drop_column]
            
    # Drop columns with more than 10% missing values
    missing_counts = df_set.isnull().sum() / len(df_set)
    d = {k:v for (k,v) in missing_counts.items() if v>0.1}
    
    for drop_column in d.keys():
        if drop_column in categorical_cols:
            categorical_cols = [x for x in categorical_cols if x not in drop_column]
        elif drop_column in numerical_cols:
            numerical_cols = [x for x in numerical_cols if x not in drop_column]
            
    return categorical_cols, numerical_cols

In [62]:
# join data
df_temp = df_set.copy()
df_temp = df_temp.join(df_labels)

### Step 3: Clean data and train model

In [70]:
categorical_cols, numerical_cols = get_feature_types(df_set)
label_map = {'non functional': 0, 'functional needs repair':1, 'functional':2}
df_labels['label'] = df_labels['status_group'].map(label_map)

class RecordedDate(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass
    def fit( self, X, y = None ):
        return self
    
    def transform(self, X, y=None):
        X["year_recording"] = pd.to_datetime(X['date_recorded']).dt.year
        X["month_recording"] = pd.to_datetime(X['date_recorded']).dt.month
        X["day_recording"] = pd.to_datetime(X['date_recorded']).dt.day
        return X
    def get_feature_names(self):
        return ['year_recording', 'month_recording', 'day_recording']

    

def preprocessing_pipeline(clf, categorical, numerical, scaler=StandardScaler(), encoder=OneHotEncoder(sparse=False, handle_unknown='ignore')):
    """ Returns a pipeline that imputes all missing values, encodes categorical features and scales numeric ones
    Keyword arguments:
    categorical -- A list of categorical column names. Example: ['gender', 'country'].
    scaler -- any scikit-learn feature scaling method (Optional)
    encoder -- any scikit-learn category encoding method (Optional)
    Returns: a scikit-learn pipeline which preprocesses the data and then runs the classifier
    """
    
    preprocessing_feat = Pipeline(steps=[
        ("feature_engineering", RecordedDate())
        ])
    
    categorical.extend(RecordedDate().get_feature_names())
    categorical.remove('date_recorded')
    
    preprocessing_cat = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encode', encoder)])
    
    preprocessing_num = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='mean')),
        ('scaler', scaler)])
    
    
    
    processing = ColumnTransformer(transformers=[
     ('cat', preprocessing_cat, categorical),
     ('num', preprocessing_num, numerical)
     ]
    )
    
    pipe = Pipeline(steps=[('feat', preprocessing_feat), 
                           ('preprocessor', processing),
                           ('clf', clf)], verbose=True)
    return pipe

### Step 4: Split data

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df_set, df_labels['label'], test_size=0.2, random_state=1)

In [20]:
# Determine class weights
df_labels['label'].value_counts() / df_labels['label'].value_counts().sum()

2    0.543081
0    0.384242
1    0.072677
Name: label, dtype: float64

### Step 5: Train model and optimize hyper-parameters

In [21]:
param_grid = {
        "clf__n_estimators": [10000],
        "clf__learning_rate": [0.01],
        "clf__num_leaves": [100],
        "clf__max_depth": [8, 10, 12]
    }


pipe = preprocessing_pipeline(lgb.LGBMClassifier(class_weight={0:0.25, 1:0.5 , 2:0.25}), categorical_cols, numerical_cols)
search = GridSearchCV(pipe, param_grid, n_jobs=-1, scoring='f1_weighted')
search.fit(X_train, y_train)

print("Best parameter (CV score=%0.3f):" % search.best_score_)
print(search.best_params_)

[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   1.4s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.2min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.1s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.6s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 1.1min
Best parameter (CV score=0.784):
{'clf__learning_rate': 0.01, 'clf__max_depth': 8, 'clf__n_estimators': 10000, 'clf__num_leaves': 100}

In [22]:
print("Best parameter (CV score=%0.3f):" % search.best_score_)
print(search.best_params_)

Best parameter (CV score=0.784):
{'clf__learning_rate': 0.01, 'clf__max_depth': 8, 'clf__n_estimators': 10000, 'clf__num_leaves': 100}
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.8s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 3.3min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.9s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.0min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.8s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 3.2min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.1s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   1.0s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.0min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   1.5s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 3.2min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.9s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.5min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.8s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 3.3min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.9s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.6min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   1.1s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 3.3min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   1.0s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 5.9min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   1.4s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.1min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.9s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.2min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.0s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   1.5s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.2min
[Pipeline] .............. (step 1 of 3) Processing feat, total=   0.1s
[Pipeline] ...... (step 2 of 3) Processing preprocessor, total=   0.9s
[Pipeline] ............... (step 3 of 3) Processing clf, total= 4.3min

### Step 6: Save model for deployment

In [ ]:
joblib.dump(search.best_estimator_, 'lightgdm_default_0805.pkl')